### ISSUE TITLE
An additional feature for replacement transformation

### ISSUE THREAD

**Issue by ustc-zzzz** [rojo8399/PlaceholderAPI#18]
I want to add a feature for [my plugin](https://github.com/ustc-zzzz/VirtualChest) that server admins could write single-line scripts such as `%economy_balance_dollar% > 20` or `%player_perm_a.b.c% == 'true'`, while I noticed something that needed to be done: there could be some weird characters such as single quotes and double quotes which should be escaped (`' => \'`, `" => \"`, etc.) in order to avoid potential injection attacks.

So I request for a feature about transformation of the replacements, and the API might be like this:
```java
Text replacePlaceholders(Player player, String text, Function<? super Text, ? extends Text> mappingFunction);
String replacePlaceholdersLegacy(Player player, String text, Function<? super Text, ? extends String> mappingFunction);
```
and then I could pass the escape function and everything works well.

Thanks for your attention!

**Comment by Wundero** [comment]
I'm not particularly sure what you mean by injection attacks. I have tested the parsing feature both with Java code and in-game and it handles special characters just fine. If you try it for yourself using `%player_perm_a.b.c% == 'true'`, the parser will return `TRUE == 'true'`.

**Comment by ustc-zzzz** [comment]
Well...I do not mean that there might be an injection attack in your plugin. I just request for a feature...You may be confused by the excessive information I have provided. Let me explain further.

--------

I want to use the PlaceholderAPI in my plugin for one-line scripts. For example, If a server admin wants to check if the player's display name is 'Notch', maybe he or she will write this: 
`%player_displayname% == 'Notch'`

However, it doesn't work, because after the process of PlaceholderAPI, it will be like this:
`Dinnerbone == 'Notch'`
and Dinnerbone is not a valid variable.

So the server admin may write this:
`'%player_displayname%' == 'Notch'`
but if a player's display name is like this: `', /* do something evil */, 'Notch`,
it will be like this after the process of PlaceholderAPI:
`'', /* do something evil */, 'Notch' == 'Notch'`
and it causes the injection attack.

--------

So I request for a feature that I could transform the replacement provided by the PlaceholderAPI by passing a function by **myself**. For example:
```java
public Text theFunction(Text replacement)
{
    // escape function, the single quote will be replaced by \' instead
    // and the text will be surrounded by a pair of single quotes
}
```
and the server admin just write:
`%player_displayname% == 'Notch'`
the final string will be:
`'Dinnerbone' == 'Notch'`
`'\', /* do something evil */, \'Notch' == 'Notch'`
and everything works well.

**Comment by Wundero** [comment]
I see now that, in your scripts, you could run into issues where injection attacks could happen, however I feel as though the escape function is such a niche use case that it's not something that should be implemented in this API. The problem is that the developers who implement the backend of the API (that is, who create placeholders and the service off of which you retrieve placeholders) are not sure what exactly the function expects of them. This issue came up a while ago when I had tried to implement support for choosing which text parser the API would use to serialize and deserialize texts, and it caused more problems than it solved. 

Something like escaping special characters in a `Text` object may be more fitting to request of the Sponge API than us simply because that could have a lot more use cases than if it was contained within our plugin.

**Comment by ustc-zzzz** [comment]
Well, I found the solution.

I found the `PlaceholderService#fillPlaceholders` method and I could try to transform the return value and then apply them to a `TextTemplate`.

Anyway, thank you for your nice plugin!
