### ISSUE TITLE
Source required to replace placeholder?

### ISSUE THREAD

**Issue by randombyte-developer** [rojo8399/PlaceholderAPI#30]
Hi!

I would like to integrate PAPI into the plugin Holograms. These holograms are just ArmorStand with custom names, no packet magic is done. Therefore the source for replacing placeholders can not be determined. Null is forbidden for the source. Is there any way I could integrate it?

**Comment by Wundero** [comment]
I just committed a fix that allows null for the source as far as I can tell (I will test to see if it actually works in a moment, and push any fixes if it doesn't). I will push another update soon but I have been super busy recently. I will close this issue once I've verified that null sources and observers work.

In the future though, when Contexts are properly pushed, you could have a source because displayname can be per player. Might be interesting to look into ;)

**Comment by Wundero** [comment]
Ok so it looks like I've got some more internal issues, so I am looking into that now. From now on, annotated methods will have to specify that they support nullable sources with the `@Nullable` annotation. I will update my internals accordingly.

**Comment by Wundero** [comment]
Alright, I just pushed another commit that seems to support null sources and observers as much as I can internally. Parameters with the `@Nullable` annotation CAN be null, while parameters without it are ALWAYS present. The token parameter only uses the annotation if it is a `String`, because it doesn't make sense to have a null reference for an `Optional<String>`. 

This should fix this issue but I should point out that many of the placeholders I have are dependent on having a source (such as `player` or `rank`), so there isn't too much you can do with this. I might work on the `economy` placeholder to support balance ranks that are source-independent, but I don't have enough time today so maybe another day.
