### ISSUE TITLE
Enhance Errors

### ISSUE THREAD

**Issue by ronaldburns** [rojo8399/PlaceholderAPI#32]
Thinking about catching errors when typing commands and handling them instead of Sponge so we can provide more help, and make it look good of course.

**Errors To Enhance**
- [ ] /papi {error}
- [ ] /papi enable {error}
- [ ] /papi disable {error}
- [ ] /papi parse {error}
- [ ] /papi info {error}

**Comment by Wundero** [comment]
While I am all for more specific error diagnostics, there are a couple of issues with this that we have to wait for resolutions. The first one is that the command API is changing in version 8.0. With version 8.0 we will see events and commands completely reworked, meaning this plugin will break. I am going to update for version 8.0 only (because I don't feel like maintaining multiple versions is useful). Until that happens, I would like to hold off on any command or event related fixes in case they become moot.

The other issue is that we cannot really use Sponge's advanced argument system if we want to go with our own error handling. We would effectively use the remaining strings joined and handle our own parsing which eliminates the usefulness of Sponge's system, and given that the next update to the command system will include much better error handling, usage parsing and suggestions, I think this is safe to hold off on for now, if not close. I will keep this open but I probably won't do much until I confirm that 8.0 won't overwrite what we do.

**Comment by Wundero** [comment]
So I have been working on error handling for Placeholders that don't parse properly so that they can provide suggestions and stuff; As far as commands are concerned, I realized recently just how poorly Sponge seems to handle bad inputs so I understand why error handling would be nice, however I think with 8.0 it will be fixed. Hopefully that will be the case.
