### ISSUE TITLE
SeriousVote Placeholder

### ISSUE THREAD

**Issue by GershonR** [rojo8399/PlaceholderAPI#40]
Wondering if you can add a Placeholder for SeriousVote, i.e Vote Count
https://forums.spongepowered.org/t/shipit-seriousvote-4-4-your-one-stop-votifier-listener-gift-api-5-6-7/16196

**Comment by Wundero** [comment]
I will look into this once I fix the other issues.

**Comment by Wundero** [comment]
So I have written an attempt to make a placeholder for this plugin, but it is not very safe to use. The issue is that SeriousVote is not made with the intent that other plugins can operate with it, and as such it is not friendly to get the information I need. I am able to get it right now but my code depends on the exact way the SeriousVote plugin functions right now.

I would recommend asking the author of SeriousVote to add PlaceholderAPI support with placeholders as it would make the whole process easier and would require fewer plugins be installed by server owners.

**Comment by Wundero** [comment]
I requested the feature in SeriousVote and hopefully this will be added in a coming update.

**Comment by GershonR** [comment]
Ok, thank you so much, hopefully he will incorporate PlaceholderAPI
