### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by ziceptor** [rojo8399/PlaceholderAPI#41]
when you start server
https://gist.github.com/ziceptor/0d6a5bf75b4bffc6473ec055c59b359f

PlaceholderAPI-4.2.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2732.jar
forge-1.12.2-14.23.0.2529-universal.jar

**Comment by ziceptor** [comment]
Any news

**Comment by ziceptor** [comment]
For some reason, cleared the config. 58 *placeholderapi.conf.tmp in folder. Recreate it and the problem went away. Works.

**Comment by ziceptor** [comment]
You can track it in the console to write the cause of failure ;)

**Comment by ziceptor** [comment]
Config is empty again. :( Spontaneously cleared.

**Comment by Wundero** [comment]
Not sure why this is happening for you, but for some reason null values are being inserted into your configuration files when they aren't supposed to. Hopefully the next update might help some things, and it will definitely fix the error in those logs, but I cannot confirm whether it will fix your configuration being cleared. This is an issue I have not seen before, so perhaps it was a formatting error for HOCON rather than a PlaceholderAPI specific issue, but I am unsure. When 4.3 comes out make sure you check to see if you can recreate this issue.

**Comment by ziceptor** [comment]
ok

**Comment by Wundero** [comment]
Hopefully fixed in 4.3. I will reopen this issue if something else comes up relating to null config values.
